branches:
  only:
    - master

skip_tags: true
max_jobs: 1

# Build worker image (VM template)
image: 
  - Visual Studio 2017

install:
  - C:\Python37-x64\python -m pip install -r requirements.txt

environment:
  matrix:
    - AIRFLOW_GPL_UNIDECODE: 1

cache:
  - '%LOCALAPPDATA%\pip\Cache'

build_script:
  - C:\Python37-x64\python setup.py build

test_script:
  - make test_av
